const division03 = [
  { division: '03 - Concrete', code: '030000', name: 'Concrete' },
  { division: '03 - Concrete', code: '030100', name: 'Maintenance of Concrete' },
  { division: '03 - Concrete', code: '030200', name: 'Concrete Testing' },
  { division: '03 - Concrete', code: '030300', name: 'Concrete Rehabilitation' },
  { division: '03 - Concrete', code: '030400', name: 'Concrete Restoration and Cleaning' },
  { division: '03 - Concrete', code: '030500', name: 'Common Work Results for Concrete' },
  { division: '03 - Concrete', code: '030510', name: 'Concrete Mixing and Delivery' },
  { division: '03 - Concrete', code: '031000', name: 'Concrete Forming and Accessories' },
  { division: '03 - Concrete', code: '031100', name: 'Concrete Forming' },
  { division: '03 - Concrete', code: '031200', name: 'Concrete Accessories' },
  { division: '03 - Concrete', code: '031300', name: 'Concrete Curing' },
  { division: '03 - Concrete', code: '031400', name: 'Form Liners' },
  { division: '03 - Concrete', code: '032000', name: 'Concrete Reinforcing' },
  { division: '03 - Concrete', code: '032100', name: 'Reinforcing Steel' },
  { division: '03 - Concrete', code: '032200', name: 'Welded Wire Reinforcement' },
  { division: '03 - Concrete', code: '032300', name: 'Post-Tensioned Concrete' },
  { division: '03 - Concrete', code: '033000', name: 'Cast-in-Place Concrete' },
  { division: '03 - Concrete', code: '033100', name: 'Structural Concrete' },
  { division: '03 - Concrete', code: '033200', name: 'Architectural Concrete' },
  { division: '03 - Concrete', code: '033300', name: 'Slab Finishes' },
  { division: '03 - Concrete', code: '033400', name: 'Concrete Finishing' },
  { division: '03 - Concrete', code: '033500', name: 'Lightweight Concrete Fill' },
  { division: '03 - Concrete', code: '033600', name: 'Concrete Floor Treatment' },
  { division: '03 - Concrete', code: '033700', name: 'Specialty Placed Concrete' },
  { division: '03 - Concrete', code: '034000', name: 'Precast Concrete' },
  { division: '03 - Concrete', code: '034100', name: 'Architectural Precast Concrete' },
  { division: '03 - Concrete', code: '034200', name: 'Structural Precast Concrete' },
  { division: '03 - Concrete', code: '034300', name: 'Tilt-Up Concrete' },
  { division: '03 - Concrete', code: '034500', name: 'Precast Concrete Specialties' },
  { division: '03 - Concrete', code: '035000', name: 'Cementitious Decks and Underlayments' },
  { division: '03 - Concrete', code: '035100', name: 'Cementitious Underlayments' },
  { division: '03 - Concrete', code: '035200', name: 'Lightweight Topping Slabs' },
  { division: '03 - Concrete', code: '036000', name: 'Grouting' },
  { division: '03 - Concrete', code: '036100', name: 'Non-Shrink Grouting' },
  { division: '03 - Concrete', code: '036200', name: 'Epoxy Grouting' },
  { division: '03 - Concrete', code: '037000', name: 'Mass Concrete' },
  { division: '03 - Concrete', code: '037100', name: 'Thermal Control of Mass Concrete' },
  { division: '03 - Concrete', code: '038000', name: 'Concrete Cutting and Boring' },
  { division: '03 - Concrete', code: '038100', name: 'Concrete Sawing' },
  { division: '03 - Concrete', code: '038200', name: 'Core Drilling' },
  { division: '03 - Concrete', code: '039000', name: 'Concrete Restoration and Cleaning' },
  { division: '03 - Concrete', code: '039100', name: 'Concrete Patching' },
  { division: '03 - Concrete', code: '039200', name: 'Concrete Crack Repair' },
  { division: '03 - Concrete', code: '039300', name: 'Concrete Surface Repair' },
  { division: '03 - Concrete', code: '039500', name: 'Concrete Floor Finishes and Restoration' }
];

module.exports = { division03 };
