const division01 = [
  { division: '01 - General Requirements', code: '011000', name: 'Summary' },
  { division: '01 - General Requirements', code: '012000', name: 'Price and Payment Procedures' },
  { division: '01 - General Requirements', code: '012100', name: 'Allowances' },
  { division: '01 - General Requirements', code: '012200', name: 'Unit Prices' },
  { division: '01 - General Requirements', code: '012300', name: 'Alternates' },
  { division: '01 - General Requirements', code: '013000', name: 'Administrative Requirements' },
  { division: '01 - General Requirements', code: '013100', name: 'Project Management and Coordination' },
  { division: '01 - General Requirements', code: '013200', name: 'Construction Progress Documentation' },
  { division: '01 - General Requirements', code: '013300', name: 'Submittal Procedures' },
  { division: '01 - General Requirements', code: '013400', name: 'Shop Drawings, Product Data, and Samples' },
  { division: '01 - General Requirements', code: '013500', name: 'Special Procedures' },
  { division: '01 - General Requirements', code: '013510', name: 'Special Project Procedures for Air Quality' },
  { division: '01 - General Requirements', code: '013513', name: 'Special Project Procedures for Mold Control' },
  { division: '01 - General Requirements', code: '014000', name: 'Quality Requirements' },
  { division: '01 - General Requirements', code: '014100', name: 'Regulatory Requirements' },
  { division: '01 - General Requirements', code: '014200', name: 'References' },
  { division: '01 - General Requirements', code: '014300', name: 'Source Quality Control' },
  { division: '01 - General Requirements', code: '014500', name: 'Special Inspections and Testing' },
  { division: '01 - General Requirements', code: '015000', name: 'Temporary Facilities and Controls' },
  { division: '01 - General Requirements', code: '015100', name: 'Temporary Utilities' },
  { division: '01 - General Requirements', code: '015200', name: 'Construction Facilities' },
  { division: '01 - General Requirements', code: '015300', name: 'Temporary Construction' },
  { division: '01 - General Requirements', code: '015600', name: 'Temporary Barriers and Enclosures' },
  { division: '01 - General Requirements', code: '015700', name: 'Temporary Controls' },
  { division: '01 - General Requirements', code: '015800', name: 'Project Identification' },
  { division: '01 - General Requirements', code: '015900', name: 'Temporary Tree and Plant Protection' },
  { division: '01 - General Requirements', code: '016000', name: 'Product Requirements' },
  { division: '01 - General Requirements', code: '016100', name: 'Basic Product Requirements' },
  { division: '01 - General Requirements', code: '016200', name: 'Product Options' },
  { division: '01 - General Requirements', code: '016300', name: 'Product Substitution Procedures' },
  { division: '01 - General Requirements', code: '017000', name: 'Execution and Closeout Requirements' },
  { division: '01 - General Requirements', code: '017100', name: 'Execution Requirements' },
  { division: '01 - General Requirements', code: '017300', name: 'Execution' },
  { division: '01 - General Requirements', code: '017400', name: 'Cleaning and Waste Management' },
  { division: '01 - General Requirements', code: '017700', name: 'Closeout Procedures' },
  { division: '01 - General Requirements', code: '017800', name: 'Closeout Submittals' },
  { division: '01 - General Requirements', code: '017823', name: 'Operation and Maintenance Data' },
  { division: '01 - General Requirements', code: '017839', name: 'Project Record Documents' },
  { division: '01 - General Requirements', code: '017900', name: 'Demonstration and Training' },
  { division: '01 - General Requirements', code: '018000', name: 'Facility Operation' },
  { division: '01 - General Requirements', code: '018100', name: 'Commissioning' }
];

module.exports = { division01 };
