const division07 = [
  { division: '07 - Thermal and Moisture Protection', code: '070000', name: 'Thermal and Moisture Protection' },
  { division: '07 - Thermal and Moisture Protection', code: '070100', name: 'Operation and Maintenance of Thermal and Moisture Protection' },
  { division: '07 - Thermal and Moisture Protection', code: '070200', name: 'Maintenance of Thermal and Moisture Protection' },
  { division: '07 - Thermal and Moisture Protection', code: '070500', name: 'Common Work Results for Thermal and Moisture Protection' },
  { division: '07 - Thermal and Moisture Protection', code: '070600', name: 'Schedules for Thermal and Moisture Protection' },
  { division: '07 - Thermal and Moisture Protection', code: '071000', name: 'Dampproofing and Waterproofing' },
  { division: '07 - Thermal and Moisture Protection', code: '071100', name: 'Dampproofing' },
  { division: '07 - Thermal and Moisture Protection', code: '071200', name: 'Bituminous Waterproofing' },
  { division: '07 - Thermal and Moisture Protection', code: '071300', name: 'Sheet Waterproofing' },
  { division: '07 - Thermal and Moisture Protection', code: '071400', name: 'Fluid-Applied Waterproofing' },
  { division: '07 - Thermal and Moisture Protection', code: '071500', name: 'Water Repellents' },
  { division: '07 - Thermal and Moisture Protection', code: '071600', name: 'Cementitious Waterproofing' },
  { division: '07 - Thermal and Moisture Protection', code: '071700', name: 'Bentonite Panel Waterproofing' },
  { division: '07 - Thermal and Moisture Protection', code: '072000', name: 'Thermal Protection' },
  { division: '07 - Thermal and Moisture Protection', code: '072100', name: 'Thermal Insulation' },
  { division: '07 - Thermal and Moisture Protection', code: '072200', name: 'Roof and Deck Insulation' },
  { division: '07 - Thermal and Moisture Protection', code: '072300', name: 'Board Insulation' },
  { division: '07 - Thermal and Moisture Protection', code: '072400', name: 'Blown Insulation' },
  { division: '07 - Thermal and Moisture Protection', code: '072500', name: 'Insulating Concrete Forms' },
  { division: '07 - Thermal and Moisture Protection', code: '072600', name: 'Vapor Retarders' },
  { division: '07 - Thermal and Moisture Protection', code: '072700', name: 'Air Barriers' },
  { division: '07 - Thermal and Moisture Protection', code: '073000', name: 'Shingles and Roofing Tiles' },
  { division: '07 - Thermal and Moisture Protection', code: '073100', name: 'Asphalt Shingles' },
  { division: '07 - Thermal and Moisture Protection', code: '073200', name: 'Clay Tile Roofing' },
  { division: '07 - Thermal and Moisture Protection', code: '073300', name: 'Concrete Tile Roofing' },
  { division: '07 - Thermal and Moisture Protection', code: '074000', name: 'Roofing and Siding Panels' },
  { division: '07 - Thermal and Moisture Protection', code: '074100', name: 'Metal Roof Panels' },
  { division: '07 - Thermal and Moisture Protection', code: '074200', name: 'Metal Wall Panels' },
  { division: '07 - Thermal and Moisture Protection', code: '074600', name: 'Siding' },
  { division: '07 - Thermal and Moisture Protection', code: '075000', name: 'Membrane Roofing' },
  { division: '07 - Thermal and Moisture Protection', code: '075100', name: 'Built-Up Bituminous Roofing' },
  { division: '07 - Thermal and Moisture Protection', code: '075200', name: 'Modified Bituminous Membrane Roofing' },
  { division: '07 - Thermal and Moisture Protection', code: '075300', name: 'Elastomeric Membrane Roofing' },
  { division: '07 - Thermal and Moisture Protection', code: '075400', name: 'Thermoplastic Membrane Roofing' },
  { division: '07 - Thermal and Moisture Protection', code: '075600', name: 'Vegetated Roofing' },
  { division: '07 - Thermal and Moisture Protection', code: '076000', name: 'Flashing and Sheet Metal' },
  { division: '07 - Thermal and Moisture Protection', code: '076100', name: 'Sheet Metal Roofing' },
  { division: '07 - Thermal and Moisture Protection', code: '076200', name: 'Sheet Metal Flashing and Trim' },
  { division: '07 - Thermal and Moisture Protection', code: '077000', name: 'Roof Specialties and Accessories' },
  { division: '07 - Thermal and Moisture Protection', code: '077100', name: 'Roof Specialties' },
  { division: '07 - Thermal and Moisture Protection', code: '077200', name: 'Roof Accessories' },
  { division: '07 - Thermal and Moisture Protection', code: '078000', name: 'Fire and Smoke Protection' },
  { division: '07 - Thermal and Moisture Protection', code: '078100', name: 'Applied Fireproofing' },
  { division: '07 - Thermal and Moisture Protection', code: '078200', name: 'Board Fireproofing' },
  { division: '07 - Thermal and Moisture Protection', code: '078300', name: 'Intumescent Fireproofing' },
  { division: '07 - Thermal and Moisture Protection', code: '079000', name: 'Joint Sealants' },
  { division: '07 - Thermal and Moisture Protection', code: '079100', name: 'Preformed Joint Seals' },
  { division: '07 - Thermal and Moisture Protection', code: '079200', name: 'Sealant Joints' }
];

module.exports = { division07 };
