const division02 = [
  { division: '02 - Existing Conditions', code: '020000', name: 'Existing Conditions' },
  { division: '02 - Existing Conditions', code: '020100', name: 'Maintenance of Existing Conditions' },
  { division: '02 - Existing Conditions', code: '020200', name: 'Assessment of Existing Conditions' },
  { division: '02 - Existing Conditions', code: '020300', name: 'Subsurface Investigation' },
  { division: '02 - Existing Conditions', code: '020500', name: 'Common Work Results for Existing Conditions' },
  { division: '02 - Existing Conditions', code: '020600', name: 'Schedules for Existing Conditions' },
  { division: '02 - Existing Conditions', code: '020700', name: 'Equipment for Existing Conditions' },
  { division: '02 - Existing Conditions', code: '020800', name: 'Commissioning of Existing Conditions' },
  { division: '02 - Existing Conditions', code: '020900', name: 'Demolition' },
  { division: '02 - Existing Conditions', code: '020910', name: 'Selective Demolition' },
  { division: '02 - Existing Conditions', code: '020930', name: 'Structure Demolition' },
  { division: '02 - Existing Conditions', code: '020950', name: 'Utility Demolition' },
  { division: '02 - Existing Conditions', code: '021000', name: 'Site Remediation' },
  { division: '02 - Existing Conditions', code: '021010', name: 'Subsurface Remediation' },
  { division: '02 - Existing Conditions', code: '021020', name: 'Soil Stabilization' },
  { division: '02 - Existing Conditions', code: '021030', name: 'Groundwater Remediation' },
  { division: '02 - Existing Conditions', code: '021040', name: 'Soil Vapor Extraction' },
  { division: '02 - Existing Conditions', code: '021050', name: 'Contaminated Soil Removal' },
  { division: '02 - Existing Conditions', code: '021060', name: 'Hazardous Waste Handling' },
  { division: '02 - Existing Conditions', code: '021070', name: 'Hazardous Material Abatement' },
  { division: '02 - Existing Conditions', code: '021080', name: 'Asbestos Abatement' },
  { division: '02 - Existing Conditions', code: '021081', name: 'Lead-Based Paint Abatement' },
  { division: '02 - Existing Conditions', code: '021082', name: 'PCBs and Heavy Metals Abatement' },
  { division: '02 - Existing Conditions', code: '021083', name: 'Mold Remediation' },
  { division: '02 - Existing Conditions', code: '021084', name: 'Decontamination and Disposal' },
  { division: '02 - Existing Conditions', code: '021100', name: 'Underground Storage Tank Removal' },
  { division: '02 - Existing Conditions', code: '021200', name: 'Environmental Site Assessment' },
  { division: '02 - Existing Conditions', code: '021300', name: 'Archaeological Survey' },
  { division: '02 - Existing Conditions', code: '021400', name: 'Site Surveying' },
  { division: '02 - Existing Conditions', code: '021410', name: 'Topographic Surveying' },
  { division: '02 - Existing Conditions', code: '021420', name: 'Property Line Surveying' },
  { division: '02 - Existing Conditions', code: '021430', name: 'Utility Surveying' },
  { division: '02 - Existing Conditions', code: '021500', name: 'Tree Removal and Protection' },
  { division: '02 - Existing Conditions', code: '021600', name: 'Temporary Site Controls' },
  { division: '02 - Existing Conditions', code: '021700', name: 'Site De-watering' }
];

module.exports = { division02 };
