// BuildX Trade Seed: FULL Division 09 - Finishes (CSI Standard)
// Covers framing, gypsum, ceilings, tile, coatings, flooring, wall panels, specialties

const division09 = [
  { division: '09 - Finishes', code: '090000', name: 'Finishes' },
  { division: '09 - Finishes', code: '090100', name: 'Operation and Maintenance of Finishes' },
  { division: '09 - Finishes', code: '090200', name: 'Maintenance of Finishes' },
  { division: '09 - Finishes', code: '090500', name: 'Common Work Results for Finishes' },
  { division: '09 - Finishes', code: '090600', name: 'Schedules for Finishes' },
  { division: '09 - Finishes', code: '091000', name: 'Non-Structural Metal Framing' },
  { division: '09 - Finishes', code: '091100', name: 'Steel Stud Framing' },
  { division: '09 - Finishes', code: '091200', name: 'Furring and Furring Channels' },
  { division: '09 - Finishes', code: '092000', name: 'Plaster and Gypsum Board' },
  { division: '09 - Finishes', code: '092100', name: 'Plaster' },
  { division: '09 - Finishes', code: '092200', name: 'Supports for Plaster and Gypsum Board' },
  { division: '09 - Finishes', code: '092400', name: 'Portland Cement Plastering' },
  { division: '09 - Finishes', code: '092500', name: 'Gypsum Board' },
  { division: '09 - Finishes', code: '092600', name: 'Sheathing' },
  { division: '09 - Finishes', code: '092700', name: 'Glass-Fiber-Reinforced Gypsum' },
  { division: '09 - Finishes', code: '093000', name: 'Tiling' },
  { division: '09 - Finishes', code: '093100', name: 'Ceramic Tiling' },
  { division: '09 - Finishes', code: '093200', name: 'Stone Tiling' },
  { division: '09 - Finishes', code: '093300', name: 'Quarry Tiling' },
  { division: '09 - Finishes', code: '094000', name: 'Terrazzo Flooring' },
  { division: '09 - Finishes', code: '094100', name: 'Cementitious Terrazzo' },
  { division: '09 - Finishes', code: '094200', name: 'Resinous Terrazzo' },
  { division: '09 - Finishes', code: '095000', name: 'Acoustical Ceilings' },
  { division: '09 - Finishes', code: '095100', name: 'Acoustical Panel Ceilings' },
  { division: '09 - Finishes', code: '095200', name: 'Acoustical Tile Ceilings' },
  { division: '09 - Finishes', code: '096000', name: 'Flooring' },
  { division: '09 - Finishes', code: '096100', name: 'Resilient Flooring' },
  { division: '09 - Finishes', code: '096200', name: 'Carpet' },
  { division: '09 - Finishes', code: '096300', name: 'Wood Flooring' },
  { division: '09 - Finishes', code: '096400', name: 'Stone Flooring' },
  { division: '09 - Finishes', code: '096500', name: 'Specialty Flooring' },
  { division: '09 - Finishes', code: '096600', name: 'Static-Control Flooring' },
  { division: '09 - Finishes', code: '096700', name: 'Fluid-Applied Flooring' },
  { division: '09 - Finishes', code: '096800', name: 'Tile Carpeting' },
  { division: '09 - Finishes', code: '097000', name: 'Wall Finishes' },
  { division: '09 - Finishes', code: '097100', name: 'Wall Panels' },
  { division: '09 - Finishes', code: '097200', name: 'Vinyl Wall Coverings' },
  { division: '09 - Finishes', code: '097300', name: 'Wall Coverings' },
  { division: '09 - Finishes', code: '098000', name: 'Acoustic Treatment' },
  { division: '09 - Finishes', code: '099000', name: 'Painting and Coating' },
  { division: '09 - Finishes', code: '099100', name: 'Paints and Coatings' },
  { division: '09 - Finishes', code: '099200', name: 'High-Performance Coatings' },
  { division: '09 - Finishes', code: '099300', name: 'Stains and Transparent Finishes' },
  { division: '09 - Finishes', code: '099600', name: 'Special Coatings' }
];

module.exports = { division09 };
